import type { Client, Payment, WorkTask } from './types'

export const clients: Client[] = [
  {
    id: 'client-001',
    name: 'Amina Wekesa',
    company: 'Blue Canopy Studio',
    email: 'amina@example.com',
    status: 'active',
    joinedOn: '2026-05-14',
  },
  {
    id: 'client-002',
    name: 'David Kimani',
    company: 'Northstar Logistics',
    email: 'david@example.com',
    status: 'active',
    joinedOn: '2026-06-02',
  },
  {
    id: 'client-003',
    name: 'Grace Otieno',
    company: 'Kijani Foods',
    email: 'grace@example.com',
    status: 'active',
    joinedOn: '2026-06-19',
  },
  {
    id: 'client-004',
    name: 'Brian Mwangi',
    company: 'Rift Digital',
    email: 'brian@example.com',
    status: 'paused',
    joinedOn: '2026-07-03',
  },
  {
    id: 'client-005',
    name: 'Leila Hassan',
    company: 'Coastline Events',
    email: 'leila@example.com',
    status: 'active',
    joinedOn: '2026-07-21',
  },
]

export const tasks: WorkTask[] = [
  {
    id: 'task-001',
    clientId: 'client-001',
    title: 'Prepare brand asset package',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2026-08-19',
  },
  {
    id: 'task-002',
    clientId: 'client-002',
    title: 'Review logistics dashboard',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-08-22',
  },
  {
    id: 'task-003',
    clientId: 'client-003',
    title: 'Deliver performance report',
    status: 'done',
    priority: 'medium',
    dueDate: '2026-08-12',
  },
  {
    id: 'task-004',
    clientId: 'client-004',
    title: 'Confirm portal requirements',
    status: 'todo',
    priority: 'low',
    dueDate: '2026-08-28',
  },
  {
    id: 'task-005',
    clientId: 'client-005',
    title: 'Build event landing page',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2026-08-20',
  },
  {
    id: 'task-006',
    clientId: 'client-001',
    title: 'Approve campaign copy',
    status: 'done',
    priority: 'low',
    dueDate: '2026-08-10',
  },
  {
    id: 'task-007',
    clientId: 'client-003',
    title: 'Draft product launch timeline',
    status: 'todo',
    priority: 'high',
    dueDate: '2026-08-25',
  },
]

export const payments: Payment[] = [
  {
    id: 'payment-001',
    clientId: 'client-001',
    description: 'Brand identity milestone',
    amount: 85000,
    status: 'paid',
    dueDate: '2026-07-30',
    paidOn: '2026-07-29',
  },
  {
    id: 'payment-002',
    clientId: 'client-002',
    description: 'Dashboard development',
    amount: 145000,
    status: 'pending',
    dueDate: '2026-08-24',
  },
  {
    id: 'payment-003',
    clientId: 'client-003',
    description: 'Monthly reporting',
    amount: 72000,
    status: 'overdue',
    dueDate: '2026-08-10',
  },
  {
    id: 'payment-004',
    clientId: 'client-005',
    description: 'Event website deposit',
    amount: 110000,
    status: 'pending',
    dueDate: '2026-08-27',
  },
  {
    id: 'payment-005',
    clientId: 'client-001',
    description: 'Campaign consultation',
    amount: 55000,
    status: 'paid',
    dueDate: '2026-08-05',
    paidOn: '2026-08-04',
  },
]